/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKIO_H
#define _MOCKIO_H

#include "unity.h"
#include "IO.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockIO_Init(void);
void MockIO_Destroy(void);
void MockIO_Verify(void);




#define IO_Read_ExpectAndReturn(addr, cmock_retval) IO_Read_CMockExpectAndReturn(__LINE__, addr, cmock_retval)
void IO_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ioAddress addr, ioData cmock_to_return);
#define IO_Write_Expect(addr, data) IO_Write_CMockExpect(__LINE__, addr, data)
void IO_Write_CMockExpect(UNITY_LINE_TYPE cmock_line, ioAddress addr, ioData data);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
