TARGET= SoundexTest
TARGET_SRC=$(TARGET)17.cpp

SRCS= $(TARGET_SRC) \
      Soundex11.cpp
      #Soundex10.cpp

INCLUDE_DIRS= ../Include
INCLUDE_FILE= Soundex05.h

INCLUDE_FILES= $(INCLUDE_DIRS)/$(INCLUDE_FILE)
INCLUDES= -I$(INCLUDE_DIRS)

include ../Makefile.mk
