TARGET= SoundexTest
TARGET_SRC=$(TARGET)18.cpp
SRCS= $(TARGET_SRC) \
      Soundex12.cpp
      #Soundex11.cpp
      #Soundex10.cpp
INCLUDE_FILE= Soundex06.h
      #Soundex05.h
INCLUDE_DIRS= ../Include

include ../Makefile.mk
