TARGET= SoundexTest
TARGET_SRC=$(TARGET)28.cpp

SRCS= $(TARGET_SRC) main.cpp \
      Soundex20.cpp
      #Soundex19.cpp
      #Soundex18.cpp
      #Soundex17.cpp
      #Soundex16.cpp
      #Soundex15.cpp
      #Soundex14.cpp
      #Soundex13.cpp
      #Soundex12.cpp
      #Soundex11.cpp
      #Soundex10.cpp

INCLUDE_FILE= Soundex11.h
      #Soundex10.h
      #Soundex09.h
      #Soundex07.h
      #Soundex06.h
      #Soundex05.h

include ../Makefile.mk
