TARGET= SoundexTest
TARGET_SRC=$(TARGET)24.cpp

SRCS= $(TARGET_SRC) main.cpp \
      Soundex17.cpp
      #Soundex16.cpp
      #Soundex15.cpp
      #Soundex14.cpp
      #Soundex13.cpp
      #Soundex12.cpp
      #Soundex11.cpp
      #Soundex10.cpp

INCLUDE_FILE= Soundex09.h
      #Soundex07.h
      #Soundex06.h
      #Soundex05.h

INCLUDE_DIRS= ../Include

include ../Makefile.mk
